PyCQA/pep8-naming

- pep8ext_naming.py
- testsuite/N802.py
This configuration option allows to skip certain function names.
This fixes https://github.com/flintwork/pep8-naming/issues/6
Consider this a WIP. If the approach is ok I will add the same logic to other error types, namely:
- N801 class names should use CapWords convention *TBD (you can not always control this)*
- N802 function name should be lowercase **(done)**
- N803 argument name should be lowercase *TBD (ditto as 801)*
- N806 variable in function should be lowercase *I don't think it makes sense, right?*
Any other error should be also check for names to skip?
> Add ignore-names option

- pep8ext_naming.py
[As noted on this commit][0], the default ignored names were combined using `','.join` and then split using `.split(', ')` which was not splitting the names correctly. 
```
>>> ','.join(['foo', 'bar']).split(', ')
['foo,bar']
```
This adjusts the splitting to allow both space and commas.
[0]: https://github.com/flintwork/pep8-naming/commit/984f603dbd94ebfa291bbcb3cf32be61bfbe74ee#commitcomment-11799619
> Fix the way ignored names are split

- .travis.yml
- tox.ini
Builds of https://github.com/PyCQA/pep8-naming/pull/24 and https://github.com/PyCQA/pep8-naming/pull/22 are failing because virtualenv dropped support for python 3.2.
As noted [here](https://github.com/pypa/pip/issues/3796), only 0.07% of pip traffic is initiated by users of Python 3.2, so I think it's entirely viable to drop support for Python 3.2. 
Alternatively, `.travis.yml` can be changed by pinning the version of virtualenv (https://github.com/travis-ci/travis-ci/issues/5485):
```
-  - pip install travis
+  - pip install travis "virtualenv<14.0.0"
```
> Fix failing builds on Python 3.2

- MANIFEST.in
Add license file to `MANIFEST.in` to ensure it is included in packages.
> Include license

- pep8ext_naming.py
- testsuite/N804.py
- testsuite/N805.py
According to pep 0487, the `__init_subclass__` method is implicitly
considered a classmethod. Thus it should be considered as an exception
of N804/N805 (first argument should be named self/cls). This is already
implemented for `__new__` so extend using the same logic.
> Correct N804/N805 for __init_subclass__

- run_tests.py
to avoid DeprecationWarnings with Python 3.6
> make some regexps raw strings

- .travis.yml
- tox.ini
Yesterday marks 3 years since the last release of Python 2.6! 🎉
To celebrate, I'm attempting to drop support for it from 156 prominent Python packages (one for every week it's past end-of-life)--including this one!
> Drop Python 2.6 support

- pep8ext_naming.py
- run_tests.py
- setup.py
- testsuite/N804.py
- testsuite/N805.py
- Add classmethod-decorator and staticmethod-decorator config parameters
- Add support for parsing CLI-style flake8-config parameters in testing
framework.
- Remove support for multiple `codes` in a testcase, since it was never used.
- Add tests for late-decorated methods
Fixes #38
> Add configurable list of classmethod / staticmethod decorators

- pep8ext_naming.py
- testsuite/N804.py
- testsuite/N805.py
It's a widely used (but perhaps not official?) convention to consider a
metaclass's methods to be class methods and to use `cls` as the first
argument (rather than `self`).
Use the simple heuristic of "class inherits from `type`" to identify
metaclasses and mark all of their methods as `CLASSMETHOD`.
> Consider all metaclass methods to be class methods

- src/pep8ext_naming.py
- testsuite/N804.py
This should avoid attribute errors for checking the ``id`` attribute on
classes that don't have a basic inheritance declaration.
Closes gh-53
> Only check ast.Name for their id in metaclass check

- src/pep8ext_naming.py
This fixes a bug where ignoring names won't work with class names.
Unfortunately I can't add a test, because options will carry over to the next test, breaking other tests.
Is it possible to release this fix soon?
> fix ignore bug in class names

- src/pep8ext_naming.py
Currently, N81x reports the "imported as" name as the name in its `'{name}' imported as` messages which isn't quite correct, because it's not the "imported as" name that was imported, it's the original name. This causes confusing error messages such as:
> N814 camelcase 'KEYLEN' imported as constant
...for which the immediate reaction at least for me is "w00t, KEYLEN is **_not_** camelcase???".
A step towards the right direction is to use the original name as the reported name that was imported, that's implemented by the first commit in this patch set. The two remaining commits improve this further, by first making it possible to have multiple variables in message format strings, and then reporting both the original and the imported name for N81x.
> N81x message improvements

- run_tests.py
- src/pep8ext_naming.py
- testsuite/N801_py3.py
- testsuite/N802_py3.py
- testsuite/N803_py3.py
- testsuite/N806_py3.py
- testsuite/N807_py3.py
- testsuite/N81x_py3.py
Note: Non-ASCII identifiers are a py3-only feature (PEP 3131).
run_tests.py:
Open files using io.open and utf8 encoding. (python2's built-in open
does not have the encoding parameter.)
pep8ext_naming.py:
Remove global case-checking regexes. Use the equivalent str methods
which also handle non-ascii characters properly.
testsuite/:
Add tests for non-ascii identifiers.
Fix issue #37.
> Fix casing detection for non-ascii characters

- src/pep8ext_naming.py
- testsuite/N801.py
name.lstrip('_')[0] may raise an IndexError if the name is `_`.
Thanks to @jparise for seeing this bug.
> Fix a bug in ClassNameCheck

- src/pep8ext_naming.py
- testsuite/N802.py
Django [provides](https://docs.djangoproject.com/en/2.0/topics/testing/tools/#django.test.TestCase.setUpTestData) a method called `setUpTestData` in its unittest extension class.
Here goes the fix to allow projects using django and `setUpTestData` use this awesome library.
> N802: Ignore Django setUpTestData method in

- run_tests.py
- src/pep8ext_naming.py
- testsuite/N801.py
- testsuite/N801_py3.py
- testsuite/N802.py
- testsuite/N803.py
- testsuite/N804.py
- testsuite/N805.py
- testsuite/N806.py
- testsuite/N807.py
- testsuite/N815.py
- testsuite/N816.py
- testsuite/N81x.py
pep8ext_naming._err:
col_offset was zero-indexed, use a 1-indexed value which is more common.
pep8ext_naming.FunctionArgNamesCheck.visit_functiondef:
Calling self.err(function_node, ...) for argument, used to results in
wrong column offset. Make a few changes in get_arg_names and rename it
to get_arg_name_tuples, so that we can call self.err using argument
node directly.
With this change the wrong argument offset for N803, N804, and N805
will be fixed in Python 3.
Note that Python 2 does not provide the exact location (node) for *args
and **kwargs, as before, the function node is returned instead.
runtests.py:
Implement a way to test for the line number and column offset in returned
errors. Now developers will be able to add rules in `#: code:line:column`
format. Specifying line and …
> Test and fix column numbers

- src/pep8ext_naming.py
- testsuite/N807.py
PEP-562 adds support for module-level `__getattr__` and `__dir__`
functions. Don't flag them as N807 function name violations.
> Support module __getattr__ and __dir__ functions

- src/pep8ext_naming.py
- testsuite/N81x.py
> Catch N81x errors in `import x as y` statements

- src/pep8ext_naming.py
- testsuite/N81x.py
This supports the common case of importing common utility routines (such
as Django's gettext functions) as `_` for convenience.
Fixes #92
> Allow lowercase names to be imported as _

- README.rst
- src/pep8ext_naming.py
- testsuite/N815.py
`ignore-names` was previously only checked for N802 errors. This change
extends the code to also consider `ignore-names` for the N806, N815, and
N816 checks.
The default set of names has been extended to include some camelCase
names from the `unittest` package that may appear in user code:
- failureException
- longMessage
- maxDiff
Fixes #93
> Honor ignore-names in the variable names checks

- src/pep8ext_naming.py
- testsuite/N803.py
It's common for some arguments to be named `_`, often to indicate that
they're unused. Previously, our "is lowercase" check would fail on these
cases.
Fixes #95
> Allow function arguments to be named _

- .travis.yml
- tox.ini
Also move the Python 3 flake8 test environment to Python 3.7 so that it
tests against the latest language grammar (including async/await, for
example).
> Add py36 and py37 environments to tox.ini

- src/pep8ext_naming.py
- testsuite/N806_py2.py
In Python 2, it's legal to receive and unpack a tuple as an exception
value:
except (socket.herror, socket.gaierror) as (errno, errstring):
This is in fact the documented exception value of some socket functions:
- https://docs.python.org/2/library/socket.html#socket.herror
- https://docs.python.org/2/library/socket.html#socket.gaierror
Fixes #98
> Support tuples of ast.ExceptHandler names

- tox.ini
This verifies the integrity of the setup metadata so we can be even more
confident in our PyPI releases.
> Check reStructuredText syntax along with flake8

- CHANGELOG.rst
- src/pep8ext_naming.py
- testsuite/N801.py
- testsuite/N802.py
- testsuite/N806.py
- testsuite/N807.py
- testsuite/N815.py
- testsuite/N816.py
cls.ignore_names starts life as a list, which is used as the default
value for the ignore-names option, and then it becomes a frozenset()
once the option is set.
Unfortunately, when flake8's --config option is used, it appears we run
those this sequence more than once, and that results in the frozenset()
being passed as the option's default value, which breaks flake8.
This change moves the default ignore-names list to a module-level
constant alongside the other default lists. This avoids the problem
described above and has the nice side-effect of making the code more
consistent.
> Fix ignore-names option initialization

- README.rst
- src/pep8ext_naming.py
- testsuite/N807.py
- testsuite/N807_py3.py
- testsuite/N807_py35.py
N807 previously flagged function names that started *or* ended up `__`.
Instead, relax this restriction and only flag function names that both
start *and* end with `__`.
This brings is closer to the spirit of PEP8, which states "Never invent
such names; only use them as documented." when referring to "magic"
names like `__author__`, `__import__`, `__file__`, etc., while allowing
people to prefix or suffix their functions with `__` if they like.
Fixes #51
> Relax N807 to "start *and* end with '__'"

- .travis.yml
- tox.ini
Python 3.3 and 3.4 are EOL ([3.4 as of March 2019](https://www.python.org/dev/peps/pep-0429/)), so I propose to drop support for these in Travis and Tox.
Meanwhile 3.8 is in alpha for an October release, so add this to start testing against it now.
> Remove Python 3.3/3.4 (EOL), add 3.8 (alpha)

- src/pep8ext_naming.py
- testsuite/N806_py2.py
Fix for a crash in a little-used piece of Python 2 syntax.
Apparently you can assign to an attribute in a Python 2 exception handler:
```python
except Exception as foo.bar:
```
or (same AST)
```python
except Exception, foo.bar:
```
Unfortunately pep8-naming doesn't handle this, and crashes with 
```pytb
...
File "/home/mauve/dev/pep8-naming/.tox/py27/local/lib/python2.7/site-packages/pep8ext_naming.py", line 425, in visit_excepthandler
for error in self._find_errors(node, parents, ignore):
File "/home/mauve/dev/pep8-naming/.tox/py27/local/lib/python2.7/site-packages/pep8ext_naming.py", line 385, in _find_errors
for name in _extract_names(assignment_target):
File "/home/mauve/dev/pep8-naming/.tox/py27/local/lib/python2.7/site-packages/pep8ext_naming.py", line 477, in _extract_names
yield …
```
> Handle exception assignment to attribute (py2)

- run_tests.py
Previously, we would print something like `found_errors: set(['N805'])`.
Now we print a comma-separated list of the error codes, which is a bit
nicer to read.
> Improve output formatting of found errors

- src/pep8ext_naming.py
- testsuite/N804.py
- testsuite/N805.py
This is a common metaclass base type because it comes from the standard
library. Extend our metaclass detection heuristic (#47) to recognize it.
> Recognize abc.ABCMeta as a metaclass base type

- src/pep8ext_naming.py
- testsuite/N805_py38.py
`args.posonlyargs` was added to Python 3.8's AST to represent
position-only arguments. These come first in the total ordering of a
function's argument groups, so we need to consider them inside of
get_arg_name_tuples().
This is particularly relevant to N805, which checks the name of the
first argument for methods.
Fixes #122
> Recognize Python 3.8's args.posonlyargs group

- src/pep8ext_naming.py
- testsuite/N80x.py
In Python 3.8, bpo-33211 addressed what is considered a bug where a
function or a class with a decorator would report an incorrect `lineno`
and `col_offset`.  In versions < 3.8, the first decorator line was
reported, which requires the accounted for offset.  Now, the actual
`lineno` and `col_offset` is reported by the `ast` module.
Please see https://bugs.python.org/issue33211 for reference.
> Don't offset lineno when reporting errors for Python >= 3.8

- README.rst
- src/pep8ext_naming.py
- testsuite/N804.py
- testsuite/N805.py
This would be helpful when using libraries / DSLs that have their own conventions around method args.
> Apply --ignore-names to N804 and N805

- .travis.yml
Python 3.8 has been officially released for quite some time now.
> Build using Python 3.8 instead of 3.8-dev

- src/pep8ext_naming.py
- testsuite/N805.py
We previously only looked for known metaclass base classes that were
inheriting using the simple `ast.Name` syntax:
class Meta(type): pass
class Meta(ABCMeta): pass
We weren't accounting for the `ast.Attribute` syntax:
class Meta(abc.ABCMeta): pass
This second syntax will now also match `ABCMeta` and be recognized as a
metaclass base class.
We could alternatively add `abc.ABCMeta` to METACLASS_BASES and
construct the fully-qualified name of each base class that uses the
`ast.Attribute` syntax. The simpler approach used here is currently
unambiguous, so we'll start with it.
Fixes #136
> Improve known metaclass base class detection

- src/pep8ext_naming.py
- testsuite/N806_py38.py
- testsuite/N816_py38.py
> implement visitor method for NamedExpr

- src/pep8ext_naming.py
- testsuite/N8xx_py36.py
PEP 526, syntax for variable annotations, has been introduced in
Python 3.6.
https://www.python.org/dev/peps/pep-0526/
fixes #138
> check annotated variable declarations

- src/pep8ext_naming.py
- testsuite/N805.py
According to PEP 560:
> The __class_getitem__ is automatically a class method and does not
> require @classmethod decorator (similar to __init_subclass__) and is
> inherited like normal attributes.
Classify this name the same way we do `__new__` and `__init_subclass__`.
Fixes #144
> Recognize __class_getitem__ as a class method

- src/pep8ext_naming.py
- testsuite/N805.py
We only supported ast.Name nodes in functions' decorator lists. We also
need to support ast.Call (e.g. the `@decorator(arg)` syntax).
Fixes #149
> Support ast.Call nodes in decorator lists

- run_tests.py
- src/pep8ext_naming.py
We previously always ran all of our checks regardless of the configured
style guide (the set of selected and ignore error codes). Now, we build
our list of visitor classes based on which error codes they can emit and
which error codes are selected in the current style guide.
This is a (minor) performance optimization for folks who have many files
and only a subset of our checks enabled.
> Only run selected checks

- CHANGELOG.rst
- src/pep8ext_naming.py
- testsuite/N805.py
I had assumed that each node in the decorator list was either a Call or
a Name, but it can also be an Attribute when the decorator uses module
notation (e.g. `@module.decorator()`).
Fixed #152
> Fix an AttributeError when processing decorators

- README.rst
We've switched to GitHub Actions for CI.
> Remove Travis-CI badge

- README.rst
Also add anchors and pep8.org references for many of the rules.
See #165
> Reference N817 from N814, and vice-versa

- README.rst
- src/pep8ext_naming.py
- testsuite/N802.py
These are new in Python 3.8's unittest.IsolatedAsyncioTestCase.
> Exempt asyncSetUp and asyncTearDown, just like setUp and tearDown

- src/pep8ext_naming.py
- testsuite/N818.py
Because this function is recursive, it can exhaust the stack if the
class hierarchy contains duplicate names. Avoid that using simple
memoization.
Also, these two supporting functions can be classmethods because they
don't use any instance-level state.
Fixes #174
> Avoid stack exhaustion in superclass_names()

- .github/workflows/ci.yml
Both of these versions are beyond their official end-of-life.
> Remove Python 3.5 and 3.6 from the test matrix

- run_tests.py
- setup.py
- src/pep8ext_naming.py
This library was used to maintain compatibility with flake8 2.x, but
it's no longer needed now that we depend on flake8 3.9+.
> Remove flake8-polyfill

- CHANGELOG.rst
- src/pep8ext_naming.py
These warnings are visible wit flake8 4 and `flake8 --verbose`:
```
flake8.options.manager    MainProcess    169 WARNING  option --ignore-names: please update `help=` text to use %(default)s instead of %default -- this will be an error in the future
flake8.options.manager    MainProcess    170 WARNING  option --classmethod-decorators: please update `help=` text to use %(default)s instead of %default -- this will be an error in the future
flake8.options.manager    MainProcess    170 WARNING  option --staticmethod-decorators: please update `help=` text to use %(default)s instead of %default -- this will be an error in the future
```
Fixes #204
> Fix warnings related to deprecated options syntax

- README.rst
The first entry explains how to configure classmethod_decorators to recognize SQLAlchemy's class methods.
> Start a FAQ section in the README

- src/pep8ext_naming.py
- testsuite/N802.py
PEP 698 introduces the `@typing.override` decorator which indicates a method overrides a base class method. It's nice to skip naming checks in this case because the user don't have any control over the name used by the subclass.
Fixes #215
> Ignore methods decorated by @typing.override

- src/pep8ext_naming.py
- testsuite/N801.py
- testsuite/N802.py
- testsuite/N803.py
- testsuite/N804.py
- testsuite/N805.py
- testsuite/N806.py
- testsuite/N807.py
- testsuite/N815.py
- testsuite/N816.py
I created this branch to fix issue #218. While I was updating the unit tests, I found a couple of tests for N807(--ignore-names) that would have passed regardless of whether that option was included, so this PR also includes a commit that fixes those tests.
The tests that I wrote as part of this fix would only fail on Windows without the fix -- I don't see an easy way to write tests that would fail on all platforms without the fix, but I'm open to suggestions.
> Fix Issue 218: ignore-names globbing is not case-sensitive on Windows

- .github/workflows/ci.yml
- setup.py
- tox.ini
Python 3.7 reached the end of its supported life in June 2023.
> Drop support for Python 3.7

- src/pep8ext_naming.py
Rather than storing the 'parents' deque as an instance attribute, pass it as a parameter as we walk the tree.
This gives us more explicit control of this stack's lifetime (and no more mutable state on the object itself), and it allows us to better restrict the typed interface we present to visitor methods (`Iterable`).
It also might result in a micro-optimization because read a parameter value is less involved (faster) than loading an instance attribute, but that isn't the goal of this change.
> Pass 'parents' as a parameter when walking the tree

- src/pep8ext_naming.py
The previous implementation repeated the N803 (lowercase name) check three times. This change reworks the function's logic to avoid code duplication. It also let me remove some nested function calls.
In the process, I noticed two additional things that could be improved (but I'm only doing one of them here):
1. We were previously returning after the first naming error, perhaps as an optimization, but I think it's more helpful to return all of the errors we can detect from within this check.
2. The "ignored names" set is (unnecessarily?) used for the N804/N805 first argument checks. We have some test cases that expected this behavior, so I'm retaining it for backwards compatibility.
> Refactor FunctionArgNamesCheck (N803,N804,N805)

- README.rst
- src/pep8ext_naming.py
- testsuite/N808.py
Proposed implementation for #163.
Adds support for type variable name convention check, as mentioned in [PEP8](https://peps.python.org/pep-0008/#type-variable-names):
> Names of type variables introduced in [PEP 484](https://peps.python.org/pep-0484/) should normally use CapWords preferring short names: T, AnyStr, Num. It is recommended to add suffixes _co or _contra to the variables used to declare covariant or contravariant behavior correspondingly:
Proposed name is N808 due to the relationship with the class name convention.
It's my first time contributing, so please let me know if anything needs to be done differently!
Thank you
> Add support for type variable name convention check

- .github/workflows/ci.yml
- setup.py
- tox.ini
Python 3.8 reached the end of its supported life on 2024-10-07.
https://devguide.python.org/versions/
> Drop support for Python 3.8

- src/pep8ext_naming.py
Python 3.6 introduced `__init_subclass__(cls)`, which provides a nicer subclass registration pattern than the previous metaclass-based approach.
> Use __init_subclass__ for subclass registration

- src/pep8ext_naming.py
We previously constructed a frozen set of names that should be ignored at setup-time and then passed that set as an argument to each visitor function. A helper function -- _ignored(name, set) -- was used to test whether a given name should be ignored, matched using fnmatchcase().
This change introduces a `NameSet` type, which inherits from frozenset and implements `__contains__` using fnmatchcase(). This allows us to simply use the `in` operator in visitor functions.
The previous code also (sometimes) treated the `ignores` argument as optional (defaulting to None). This value always exists so remove the optional notation.
> Refactor ignored name handling

- src/pep8ext_naming.py
When the set of ignored names doesn't use shell-style wildcards, we can use the faster `frozenset.__contains__` base implementation rather than the more expensive iteration-based fnmatch'ing approach. This is true for the default ignore list, and I expect its the more common case by far even for those who add their own ignored names.
In a simple local benchmark, this results in a 2x speed improvement for that common (default) path, which I think justifies the small additional complexity.
> Add a fast path for NameSets without wildcards

- src/pep8ext_naming.py
First, represent FunctionType as an enum.Enum. This is more about the data type's concept than any higher-level Enum features.
Then use FunctionType so improve the typing of various dictionaries and function signatures.
Lastly, use setattr() for our AST monkey patching. I tried a few other approaches here (using ast.(Async)FunctionDef subclasses, introducing a new protocol, etc.), but the monkey patching approach always came out the simplest and most obvious. Using setattr() avoids typing errors related to unknown direct attribute assignments.
> FunctionType typing improvements

- src/pep8ext_naming.py
- testsuite/N808.py
This is consistent with our CapWords-based N801 class name check, which shares a similar PEP 8 definition.
Resolves #245
> Allow TypeVar names to start with an underscore
